#ifndef DECOMPILERTABLE_H
#define DECOMPILERTABLE_H

// Generated by APIGenerator 1.0
// DO NOT EDIT!!!

#include <QHash>
#include "../../../types/basic.h"
#include <QObject>
#include "../../tltypes.h"

class DecompilerTable: public QObject
{
	Q_OBJECT

	public:
		static QString constructorName(TLConstructor ctor);
	private:
		static void initConstructors();

	private:
		static QHash<TLConstructor, QString> _constructors;

};

#endif // DECOMPILERTABLE_H
