#ifndef LIBQTELEGRAM_GLOBAL_H
#define LIBQTELEGRAM_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBQTELEGRAM_LIBRARY)
#  define LIBQTELEGRAMSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBQTELEGRAMSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBQTELEGRAM_GLOBAL_H
