#ifndef FILEOBJECT_H
#define FILEOBJECT_H

#include <QObject>
#include <QFile>
#include <QSize>
#include "../autogenerated/types/types.h"
#include "../mtproto/mtprotorequest.h"
#include "../mtproto/dc/dcsessionmanager.h"

class FileObject : public QObject
{
    Q_OBJECT

    Q_PROPERTY(bool downloading READ downloading NOTIFY downloadingChanged)
    Q_PROPERTY(bool downloaded READ downloaded NOTIFY downloadedChanged)
    Q_PROPERTY(bool hasThumbnail READ hasThumbnail NOTIFY hasThumbnailChanged)
    Q_PROPERTY(QSize imageSize READ imageSize NOTIFY imageSizeChanged)
    Q_PROPERTY(QString thumbnail READ thumbnail NOTIFY thumbnailChanged)
    Q_PROPERTY(QString filePath READ filePath NOTIFY filePathChanged)

    public:
        enum DownloadMode {
            None = 0,
            Upload = 1,
            Download = 2,
            DownloadThumbnail = 3,
        };

    public:
        explicit FileObject(QObject *parent = 0);
        FileObject(const QString& storagepath, QObject *parent = 0);
        bool downloading() const;
        bool downloaded() const;
        bool hasThumbnail() const;
        QSize imageSize() const;
        QString thumbnail() const;
        QString filePath() const;
        void setDocument(Document* document);
        void setImageSize(const QSize& imagesize);
        void setThumbnailLocation(FileLocation* filelocation);
        void setFileLocation(FileLocation* filelocation);
        void setFileId(const QString& fileid);
        void setThumbnailId(const QString& thumbnailid);
        void downloadThumbnail();
        bool loadCache();

    public slots:
        void download();

    private slots:
        void onUploadFile(MTProtoReply* mtreply);

    private:
        void setDownloadMode(int downloadmode);
        bool isAutoDownloadDocument(Document* document);
        DocumentAttribute *documentAttribute(Document* document, TLConstructor attribute);
        QString extension(const UploadFile* uploadfile);
        void sendDownloadRequest();

    signals:
        void imageSizeChanged();
        void thumbnailChanged();
        void filePathChanged();
        void downloadedChanged();
        void downloadingChanged();
        void hasThumbnailChanged();
        void downloadCompleted();
        void uploadCompleted();

    private:
        QString _storagepath;
        int _downloadmode;
        Document* _document;
        FileLocation* _locthumbnail;
        FileLocation* _locfile;
        InputFileLocation* _inputfilelocation;
        DCSession* _dcsession;
        QFile* _file;
        QString _thumbnail;
        QString _filepath;
        QString _fileid;
        QString _thumbnailid;
        QSize _imagesize;
};

#endif // FILEOBJECT_H
