#ifndef QQUICKPEERIMAGE_H
#define QQUICKPEERIMAGE_H

#include <QtQuick>
#include <QColor>
#include "../autogenerated/types/types.h"
#include "qquickbaseitem.h"

class QQuickPeerImage : public QQuickBaseItem
{
    Q_OBJECT

    Q_PROPERTY(TelegramObject* peer READ peer WRITE setPeer NOTIFY peerChanged)
    Q_PROPERTY(int size READ size WRITE setSize NOTIFY sizeChanged)

    public:
        QQuickPeerImage(QQuickItem* parent = 0);
        TelegramObject* peer() const;
        int size() const;
        void setPeer(TelegramObject* peer);
        void setSize(int size);

    private:
        void initialize();
        void updateMetrics();
        void createRoundImageElement();
        void createPlaceHolderImageElement();
        QString fallbackText(TelegramObject* telegramobject);
        QString fallbackTitle(const QString& title);

    private slots:
        void reinitialize();

    signals:
        void peerChanged();
        void sizeChanged();

    private:
        TelegramObject* _peer;
        int _size;
};

#endif // QQUICKPEERIMAGE_H
