#ifndef CACHEFETCHER_H
#define CACHEFETCHER_H

#include <QObject>
#include "../autogenerated/types/types.h"
#include "../types/basic.h"
#include "../mtproto/mtprotoreply.h"

class CacheFetcher : public QObject
{
    Q_OBJECT

    public:
        explicit CacheFetcher(QObject *parent = 0);
        void getFullChat(Chat* chat);

    private slots:
        void onChatFull(MTProtoReply* mtreply);

    signals:
        void usersReceived(const TLVector<User*>& users);
        void chatFullReceived(ChatFull* chatfull);

     private:
        Update* _update;
};

#endif // CACHEFETCHER_H

