#ifndef AUTHCODETYPE_H
#define AUTHCODETYPE_H

// Generated by APIGenerator 1.0
// DO NOT EDIT!!!

#include "../../types/telegramobject.h"
#include "../../types/basic.h"

class AuthCodeType: public TelegramObject
{
	Q_OBJECT

	Q_ENUMS(Constructors)

	public:
		enum Constructors {
			ctorAuthCodeTypeSms = 0x72a3158c,
			ctorAuthCodeTypeCall = 0x741cd3e3,
			ctorAuthCodeTypeFlashCall = 0x226ccefb,
		};

	public:
		explicit AuthCodeType(QObject* parent = 0);
		virtual void read(MTProtoStream* mtstream);
		virtual void write(MTProtoStream* mtstream);
	protected:
		virtual void compileFlags();

};

#endif // AUTHCODETYPE_H
