// Generated by APIGenerator 1.0
// DO NOT EDIT!!!

#include "authcheckedphone.h"


AuthCheckedPhone::AuthCheckedPhone(QObject* parent) : TelegramObject(parent)
{
	this->_is_phone_registered = false;
	this->_constructorid = AuthCheckedPhone::CtorAuthCheckedPhone;
}

void AuthCheckedPhone::read(MTProtoStream* mtstream) 
{
	this->_constructorid = mtstream->readTLConstructor();
	
	Q_ASSERT((this->_constructorid == AuthCheckedPhone::CtorAuthCheckedPhone));
	
	if(this->_constructorid == AuthCheckedPhone::CtorAuthCheckedPhone)
		this->_is_phone_registered = mtstream->readTLBool();
}

void AuthCheckedPhone::write(MTProtoStream* mtstream) 
{
	Q_ASSERT((this->_constructorid == AuthCheckedPhone::CtorAuthCheckedPhone));
	
	this->compileFlags();
	mtstream->writeTLConstructor(this->_constructorid);
	
	if(this->_constructorid == AuthCheckedPhone::CtorAuthCheckedPhone)
		mtstream->writeTLBool(this->_is_phone_registered);
}

void AuthCheckedPhone::compileFlags() 
{
	
}

TLBool AuthCheckedPhone::isPhoneRegistered() const
{
	return this->_is_phone_registered;
}

void AuthCheckedPhone::setIsPhoneRegistered(TLBool is_phone_registered) 
{
	if(this->_is_phone_registered == is_phone_registered)
		return;

	this->_is_phone_registered = is_phone_registered;
	emit isPhoneRegisteredChanged();
}

