// Generated by APIGenerator 1.0
// DO NOT EDIT!!!

#include "authcodetype.h"

AuthCodeType::AuthCodeType(QObject* parent) : TelegramObject(parent)
{
	
}

void AuthCodeType::read(MTProtoStream* mtstream) 
{
	this->_constructorid = mtstream->readTLConstructor();
	
	Q_ASSERT((this->_constructorid == AuthCodeType::ctorAuthCodeTypeSms) ||
		 (this->_constructorid == AuthCodeType::ctorAuthCodeTypeCall) ||
		 (this->_constructorid == AuthCodeType::ctorAuthCodeTypeFlashCall));
}

void AuthCodeType::write(MTProtoStream* mtstream) 
{
	Q_ASSERT((this->_constructorid == AuthCodeType::ctorAuthCodeTypeSms) ||
		 (this->_constructorid == AuthCodeType::ctorAuthCodeTypeCall) ||
		 (this->_constructorid == AuthCodeType::ctorAuthCodeTypeFlashCall));
	
	this->compileFlags();
	mtstream->writeTLConstructor(this->_constructorid);
}

void AuthCodeType::compileFlags() 
{
	
}

