// Generated by APIGenerator 1.0
// DO NOT EDIT!!!

#include "botcommand.h"


BotCommand::BotCommand(QObject* parent) : TelegramObject(parent)
{
	this->_constructorid = BotCommand::CtorBotCommand;
}

void BotCommand::read(MTProtoStream* mtstream) 
{
	this->_constructorid = mtstream->readTLConstructor();
	
	Q_ASSERT((this->_constructorid == BotCommand::CtorBotCommand));
	
	if(this->_constructorid == BotCommand::CtorBotCommand)
	{
		this->_command = mtstream->readTLString();
		this->_description = mtstream->readTLString();
	}
}

void BotCommand::write(MTProtoStream* mtstream) 
{
	Q_ASSERT((this->_constructorid == BotCommand::CtorBotCommand));
	
	this->compileFlags();
	mtstream->writeTLConstructor(this->_constructorid);
	
	if(this->_constructorid == BotCommand::CtorBotCommand)
	{
		mtstream->writeTLString(this->_command);
		mtstream->writeTLString(this->_description);
	}
}

void BotCommand::compileFlags() 
{
	
}

TLString BotCommand::command() const
{
	return this->_command;
}

void BotCommand::setCommand(TLString command) 
{
	if(this->_command == command)
		return;

	this->_command = command;
	emit commandChanged();
}

TLString BotCommand::description() const
{
	return this->_description;
}

void BotCommand::setDescription(TLString description) 
{
	if(this->_description == description)
		return;

	this->_description = description;
	emit descriptionChanged();
}

