#ifndef CHANNELPARTICIPANTSFILTER_H
#define CHANNELPARTICIPANTSFILTER_H

// Generated by APIGenerator 1.0
// DO NOT EDIT!!!

#include "../../types/basic.h"
#include "../../types/telegramobject.h"

class ChannelParticipantsFilter: public TelegramObject
{
	Q_OBJECT

	public:
		enum Constructors {
			ctorChannelParticipantsRecent = 0xde3f3c79,
			ctorChannelParticipantsAdmins = 0xb4608969,
			ctorChannelParticipantsKicked = 0x3c37bb7a,
			ctorChannelParticipantsBots = 0xb0d1865b,
		};

	public:
		explicit ChannelParticipantsFilter(QObject* parent = 0);
		virtual void read(MTProtoStream* mtstream);
		virtual void write(MTProtoStream* mtstream);
	protected:
		virtual void compileFlags();

};

#endif // CHANNELPARTICIPANTSFILTER_H
