#ifndef CHANNELSCHANNELPARTICIPANT_H
#define CHANNELSCHANNELPARTICIPANT_H

// Generated by APIGenerator 1.0
// DO NOT EDIT!!!

#include "channelparticipant.h"
#include "user.h"
#include "../../types/basic.h"
#include "../../types/telegramobject.h"

class ChannelsChannelParticipant: public TelegramObject
{
	Q_OBJECT

	Q_PROPERTY(ChannelParticipant* participant READ participant WRITE setParticipant NOTIFY participantChanged)
	Q_PROPERTY(TLVector<User*> users READ users WRITE setUsers NOTIFY usersChanged)

	public:
		enum Constructors {
			ctorChannelsChannelParticipant = 0xd0d9b163,
		};

	public:
		explicit ChannelsChannelParticipant(QObject* parent = 0);
		virtual void read(MTProtoStream* mtstream);
		virtual void write(MTProtoStream* mtstream);
	protected:
		virtual void compileFlags();
	public:
		ChannelParticipant* participant() const;
		void setParticipant(ChannelParticipant* participant);
		const TLVector<User*>& users() const;
		void setUsers(const TLVector<User*>& users);

	signals:
		void participantChanged();
		void usersChanged();

	private:
		ChannelParticipant* _participant;
		TLVector<User*> _users;

};

#endif // CHANNELSCHANNELPARTICIPANT_H
