// Generated by APIGenerator 1.0
// DO NOT EDIT!!!

#include "channelparticipantsfilter.h"

ChannelParticipantsFilter::ChannelParticipantsFilter(QObject* parent) : TelegramObject(parent)
{
	
}

void ChannelParticipantsFilter::read(MTProtoStream* mtstream) 
{
	this->_constructorid = mtstream->readTLConstructor();
	
	Q_ASSERT((this->_constructorid == ChannelParticipantsFilter::ctorChannelParticipantsRecent) ||
		 (this->_constructorid == ChannelParticipantsFilter::ctorChannelParticipantsAdmins) ||
		 (this->_constructorid == ChannelParticipantsFilter::ctorChannelParticipantsKicked) ||
		 (this->_constructorid == ChannelParticipantsFilter::ctorChannelParticipantsBots));
}

void ChannelParticipantsFilter::write(MTProtoStream* mtstream) 
{
	Q_ASSERT((this->_constructorid == ChannelParticipantsFilter::ctorChannelParticipantsRecent) ||
		 (this->_constructorid == ChannelParticipantsFilter::ctorChannelParticipantsAdmins) ||
		 (this->_constructorid == ChannelParticipantsFilter::ctorChannelParticipantsKicked) ||
		 (this->_constructorid == ChannelParticipantsFilter::ctorChannelParticipantsBots));
	
	this->compileFlags();
	mtstream->writeTLConstructor(this->_constructorid);
}

void ChannelParticipantsFilter::compileFlags() 
{
	
}

