#ifndef CHANNELPARTICIPANTROLE_H
#define CHANNELPARTICIPANTROLE_H

// Generated by APIGenerator 1.0
// DO NOT EDIT!!!

#include "../../types/telegramobject.h"
#include "../../types/basic.h"

class ChannelParticipantRole: public TelegramObject
{
	Q_OBJECT

	Q_ENUMS(Constructors)

	public:
		enum Constructors {
			CtorChannelRoleEmpty = 0xb285a0c6,
			CtorChannelRoleModerator = 0x9618d975,
			CtorChannelRoleEditor = 0x820bfe8c,
		};

	public:
		explicit ChannelParticipantRole(QObject* parent = 0);
		virtual void read(MTProtoStream* mtstream);
		virtual void write(MTProtoStream* mtstream);
	protected:
		virtual void compileFlags();

};

#endif // CHANNELPARTICIPANTROLE_H
