// Generated by APIGenerator 1.0
// DO NOT EDIT!!!

#include "contactstatus.h"


ContactStatus::ContactStatus(QObject* parent) : TelegramObject(parent)
{
	this->_user_id = 0;
	this->_status = NULL;
	this->_constructorid = ContactStatus::ctorContactStatus;
}

void ContactStatus::read(MTProtoStream* mtstream) 
{
	this->_constructorid = mtstream->readTLConstructor();
	
	Q_ASSERT((this->_constructorid == ContactStatus::ctorContactStatus));
	
	if(this->_constructorid == ContactStatus::ctorContactStatus)
	{
		this->_user_id = mtstream->readTLInt();
		RESET_TLTYPE(UserStatus, this->_status);
		this->_status->read(mtstream);
	}
}

void ContactStatus::write(MTProtoStream* mtstream) 
{
	Q_ASSERT((this->_constructorid == ContactStatus::ctorContactStatus));
	
	this->compileFlags();
	mtstream->writeTLConstructor(this->_constructorid);
	
	if(this->_constructorid == ContactStatus::ctorContactStatus)
	{
		mtstream->writeTLInt(this->_user_id);
		Q_ASSERT(this->_status != NULL);
		this->_status->write(mtstream);
	}
}

void ContactStatus::compileFlags() 
{
	
}

TLInt ContactStatus::userId() const
{
	return this->_user_id;
}

void ContactStatus::setUserId(TLInt user_id) 
{
	if(this->_user_id == user_id)
		return;

	this->_user_id = user_id;
	emit userIdChanged();
}

UserStatus* ContactStatus::status() const
{
	return this->_status;
}

void ContactStatus::setStatus(UserStatus* status) 
{
	if(this->_status == status)
		return;

	this->_status = status;
	emit statusChanged();
}

