#ifndef CONTACTSFOUND_H
#define CONTACTSFOUND_H

// Generated by APIGenerator 1.0
// DO NOT EDIT!!!

#include "../../types/basic.h"
#include "../../types/telegramobject.h"
#include "peer.h"
#include "chat.h"
#include "user.h"

class ContactsFound: public TelegramObject
{
	Q_OBJECT

	Q_PROPERTY(TLVector<Peer*> results READ results WRITE setResults NOTIFY resultsChanged)
	Q_PROPERTY(TLVector<Chat*> chats READ chats WRITE setChats NOTIFY chatsChanged)
	Q_PROPERTY(TLVector<User*> users READ users WRITE setUsers NOTIFY usersChanged)

	Q_ENUMS(Constructors)

	public:
		enum Constructors {
			CtorContactsFound = 0x1aa1f784,
		};

	public:
		explicit ContactsFound(QObject* parent = 0);
		virtual void read(MTProtoStream* mtstream);
		virtual void write(MTProtoStream* mtstream);
	protected:
		virtual void compileFlags();
	public:
		const TLVector<Peer*>& results() const;
		void setResults(const TLVector<Peer*>& results);
		const TLVector<Chat*>& chats() const;
		void setChats(const TLVector<Chat*>& chats);
		const TLVector<User*>& users() const;
		void setUsers(const TLVector<User*>& users);

	signals:
		void resultsChanged();
		void chatsChanged();
		void usersChanged();

	private:
		TLVector<Peer*> _results;
		TLVector<Chat*> _chats;
		TLVector<User*> _users;

};

#endif // CONTACTSFOUND_H
