// Generated by APIGenerator 1.0
// DO NOT EDIT!!!

#include "exportedchatinvite.h"


ExportedChatInvite::ExportedChatInvite(QObject* parent) : TelegramObject(parent)
{
	
}

void ExportedChatInvite::read(MTProtoStream* mtstream) 
{
	this->_constructorid = mtstream->readTLConstructor();
	
	Q_ASSERT((this->_constructorid == ExportedChatInvite::CtorChatInviteEmpty) ||
		 (this->_constructorid == ExportedChatInvite::CtorChatInviteExported));
	
	if(this->_constructorid == ExportedChatInvite::CtorChatInviteExported)
		this->_link = mtstream->readTLString();
}

void ExportedChatInvite::write(MTProtoStream* mtstream) 
{
	Q_ASSERT((this->_constructorid == ExportedChatInvite::CtorChatInviteEmpty) ||
		 (this->_constructorid == ExportedChatInvite::CtorChatInviteExported));
	
	this->compileFlags();
	mtstream->writeTLConstructor(this->_constructorid);
	
	if(this->_constructorid == ExportedChatInvite::CtorChatInviteExported)
		mtstream->writeTLString(this->_link);
}

void ExportedChatInvite::compileFlags() 
{
	
}

TLString ExportedChatInvite::link() const
{
	return this->_link;
}

void ExportedChatInvite::setLink(TLString link) 
{
	if(this->_link == link)
		return;

	this->_link = link;
	emit linkChanged();
}

