#ifndef GAME_H
#define GAME_H

// Generated by APIGenerator 1.0
// DO NOT EDIT!!!

#include "../../types/basic.h"
#include "photo.h"
#include "document.h"
#include "../../types/telegramobject.h"

class Game: public TelegramObject
{
	Q_OBJECT

	Q_PROPERTY(TLInt flags READ flags WRITE setFlags NOTIFY flagsChanged)
	Q_PROPERTY(TLLong id READ id WRITE setId NOTIFY idChanged)
	Q_PROPERTY(TLLong accessHash READ accessHash WRITE setAccessHash NOTIFY accessHashChanged)
	Q_PROPERTY(TLString shortName READ shortName WRITE setShortName NOTIFY shortNameChanged)
	Q_PROPERTY(TLString title READ title WRITE setTitle NOTIFY titleChanged)
	Q_PROPERTY(TLString description READ description WRITE setDescription NOTIFY descriptionChanged)
	Q_PROPERTY(Photo* photo READ photo WRITE setPhoto NOTIFY photoChanged)
	Q_PROPERTY(Document* document READ document WRITE setDocument NOTIFY documentChanged)

	public:
		enum Constructors {
			ctorGame = 0xbdf9653b,
		};

	public:
		explicit Game(QObject* parent = 0);
		virtual void read(MTProtoStream* mtstream);
		virtual void write(MTProtoStream* mtstream);
	protected:
		virtual void compileFlags();
	public:
		TLInt flags() const;
		void setFlags(TLInt flags);
		TLLong id() const;
		void setId(TLLong id);
		TLLong accessHash() const;
		void setAccessHash(TLLong access_hash);
		TLString shortName() const;
		void setShortName(TLString short_name);
		TLString title() const;
		void setTitle(TLString title);
		TLString description() const;
		void setDescription(TLString description);
		Photo* photo() const;
		void setPhoto(Photo* photo);
		Document* document() const;
		void setDocument(Document* document);

	signals:
		void flagsChanged();
		void idChanged();
		void accessHashChanged();
		void shortNameChanged();
		void titleChanged();
		void descriptionChanged();
		void photoChanged();
		void documentChanged();

	private:
		TLInt _flags;
		TLLong _id;
		TLLong _access_hash;
		TLString _short_name;
		TLString _title;
		TLString _description;
		Photo* _photo;
		Document* _document;

};

#endif // GAME_H
