#ifndef GEOPOINT_H
#define GEOPOINT_H

// Generated by APIGenerator 1.0
// DO NOT EDIT!!!

#include "../../types/basic.h"
#include "../../types/telegramobject.h"

class GeoPoint: public TelegramObject
{
	Q_OBJECT

	Q_PROPERTY(TLDouble longitude READ longitude WRITE setLongitude NOTIFY longitudeChanged)
	Q_PROPERTY(TLDouble latitude READ latitude WRITE setLatitude NOTIFY latitudeChanged)

	public:
		enum Constructors {
			ctorGeoPointEmpty = 0x1117dd5f,
			ctorGeoPoint = 0x2049d70c,
		};

	public:
		explicit GeoPoint(QObject* parent = 0);
		virtual void read(MTProtoStream* mtstream);
		virtual void write(MTProtoStream* mtstream);
	protected:
		virtual void compileFlags();
	public:
		TLDouble longitude() const;
		void setLongitude(TLDouble longitude);
		TLDouble latitude() const;
		void setLatitude(TLDouble latitude);

	signals:
		void longitudeChanged();
		void latitudeChanged();

	private:
		TLDouble _longitude;
		TLDouble _latitude;

};

#endif // GEOPOINT_H
