#ifndef HELPAPPUPDATE_H
#define HELPAPPUPDATE_H

// Generated by APIGenerator 1.0
// DO NOT EDIT!!!

#include "../../types/basic.h"
#include "../../types/telegramobject.h"

class HelpAppUpdate: public TelegramObject
{
	Q_OBJECT

	Q_PROPERTY(TLInt id READ id WRITE setId NOTIFY idChanged)
	Q_PROPERTY(TLBool isCritical READ isCritical WRITE setIsCritical NOTIFY isCriticalChanged)
	Q_PROPERTY(TLString url READ url WRITE setUrl NOTIFY urlChanged)
	Q_PROPERTY(TLString text READ text WRITE setText NOTIFY textChanged)

	Q_ENUMS(Constructors)

	public:
		enum Constructors {
			CtorHelpAppUpdate = 0x8987f311,
			CtorHelpNoAppUpdate = 0xc45a6536,
		};

	public:
		explicit HelpAppUpdate(QObject* parent = 0);
		virtual void read(MTProtoStream* mtstream);
		virtual void write(MTProtoStream* mtstream);
	protected:
		virtual void compileFlags();
	public:
		TLInt id() const;
		void setId(TLInt id);
		TLBool isCritical() const;
		void setIsCritical(TLBool is_critical);
		TLString url() const;
		void setUrl(TLString url);
		TLString text() const;
		void setText(TLString text);

	signals:
		void idChanged();
		void isCriticalChanged();
		void urlChanged();
		void textChanged();

	private:
		TLInt _id;
		TLBool _is_critical;
		TLString _url;
		TLString _text;

};

#endif // HELPAPPUPDATE_H
