// Generated by APIGenerator 1.0
// DO NOT EDIT!!!

#include "helpinvitetext.h"


HelpInviteText::HelpInviteText(QObject* parent) : TelegramObject(parent)
{
	this->_constructorid = HelpInviteText::CtorHelpInviteText;
}

void HelpInviteText::read(MTProtoStream* mtstream) 
{
	this->_constructorid = mtstream->readTLConstructor();
	
	Q_ASSERT((this->_constructorid == HelpInviteText::CtorHelpInviteText));
	
	if(this->_constructorid == HelpInviteText::CtorHelpInviteText)
		this->_message = mtstream->readTLString();
}

void HelpInviteText::write(MTProtoStream* mtstream) 
{
	Q_ASSERT((this->_constructorid == HelpInviteText::CtorHelpInviteText));
	
	this->compileFlags();
	mtstream->writeTLConstructor(this->_constructorid);
	
	if(this->_constructorid == HelpInviteText::CtorHelpInviteText)
		mtstream->writeTLString(this->_message);
}

void HelpInviteText::compileFlags() 
{
	
}

TLString HelpInviteText::message() const
{
	return this->_message;
}

void HelpInviteText::setMessage(TLString message) 
{
	if(this->_message == message)
		return;

	this->_message = message;
	emit messageChanged();
}

