// Generated by APIGenerator 1.0
// DO NOT EDIT!!!

#include "helpappchangelog.h"


HelpAppChangelog::HelpAppChangelog(QObject* parent) : TelegramObject(parent)
{
	
}

void HelpAppChangelog::read(MTProtoStream* mtstream) 
{
	this->_constructorid = mtstream->readTLConstructor();
	
	Q_ASSERT((this->_constructorid == HelpAppChangelog::CtorHelpAppChangelogEmpty) ||
		 (this->_constructorid == HelpAppChangelog::CtorHelpAppChangelog));
	
	if(this->_constructorid == HelpAppChangelog::CtorHelpAppChangelog)
		this->_text = mtstream->readTLString();
}

void HelpAppChangelog::write(MTProtoStream* mtstream) 
{
	Q_ASSERT((this->_constructorid == HelpAppChangelog::CtorHelpAppChangelogEmpty) ||
		 (this->_constructorid == HelpAppChangelog::CtorHelpAppChangelog));
	
	this->compileFlags();
	mtstream->writeTLConstructor(this->_constructorid);
	
	if(this->_constructorid == HelpAppChangelog::CtorHelpAppChangelog)
		mtstream->writeTLString(this->_text);
}

void HelpAppChangelog::compileFlags() 
{
	
}

TLString HelpAppChangelog::text() const
{
	return this->_text;
}

void HelpAppChangelog::setText(TLString text) 
{
	if(this->_text == text)
		return;

	this->_text = text;
	emit textChanged();
}

