// Generated by APIGenerator 1.0
// DO NOT EDIT!!!

#include "importedcontact.h"


ImportedContact::ImportedContact(QObject* parent) : TelegramObject(parent)
{
	this->_user_id = 0;
	this->_client_id = 0;
	this->_constructorid = ImportedContact::CtorImportedContact;
}

void ImportedContact::read(MTProtoStream* mtstream) 
{
	this->_constructorid = mtstream->readTLConstructor();
	
	Q_ASSERT((this->_constructorid == ImportedContact::CtorImportedContact));
	
	if(this->_constructorid == ImportedContact::CtorImportedContact)
	{
		this->_user_id = mtstream->readTLInt();
		this->_client_id = mtstream->readTLLong();
	}
}

void ImportedContact::write(MTProtoStream* mtstream) 
{
	Q_ASSERT((this->_constructorid == ImportedContact::CtorImportedContact));
	
	this->compileFlags();
	mtstream->writeTLConstructor(this->_constructorid);
	
	if(this->_constructorid == ImportedContact::CtorImportedContact)
	{
		mtstream->writeTLInt(this->_user_id);
		mtstream->writeTLLong(this->_client_id);
	}
}

void ImportedContact::compileFlags() 
{
	
}

TLInt ImportedContact::userId() const
{
	return this->_user_id;
}

void ImportedContact::setUserId(TLInt user_id) 
{
	if(this->_user_id == user_id)
		return;

	this->_user_id = user_id;
	emit userIdChanged();
}

TLLong ImportedContact::clientId() const
{
	return this->_client_id;
}

void ImportedContact::setClientId(TLLong client_id) 
{
	if(this->_client_id == client_id)
		return;

	this->_client_id = client_id;
	emit clientIdChanged();
}

