// Generated by APIGenerator 1.0
// DO NOT EDIT!!!

#include "inlinebotswitchpm.h"


InlineBotSwitchPM::InlineBotSwitchPM(QObject* parent) : TelegramObject(parent)
{
	this->_constructorid = InlineBotSwitchPM::ctorInlineBotSwitchPM;
}

void InlineBotSwitchPM::read(MTProtoStream* mtstream) 
{
	this->_constructorid = mtstream->readTLConstructor();
	
	Q_ASSERT((this->_constructorid == InlineBotSwitchPM::ctorInlineBotSwitchPM));
	
	if(this->_constructorid == InlineBotSwitchPM::ctorInlineBotSwitchPM)
	{
		this->_text = mtstream->readTLString();
		this->_start_param = mtstream->readTLString();
	}
}

void InlineBotSwitchPM::write(MTProtoStream* mtstream) 
{
	Q_ASSERT((this->_constructorid == InlineBotSwitchPM::ctorInlineBotSwitchPM));
	
	this->compileFlags();
	mtstream->writeTLConstructor(this->_constructorid);
	
	if(this->_constructorid == InlineBotSwitchPM::ctorInlineBotSwitchPM)
	{
		mtstream->writeTLString(this->_text);
		mtstream->writeTLString(this->_start_param);
	}
}

void InlineBotSwitchPM::compileFlags() 
{
	
}

TLString InlineBotSwitchPM::text() const
{
	return this->_text;
}

void InlineBotSwitchPM::setText(TLString text) 
{
	if(this->_text == text)
		return;

	this->_text = text;
	emit textChanged();
}

TLString InlineBotSwitchPM::startParam() const
{
	return this->_start_param;
}

void InlineBotSwitchPM::setStartParam(TLString start_param) 
{
	if(this->_start_param == start_param)
		return;

	this->_start_param = start_param;
	emit startParamChanged();
}

