// Generated by APIGenerator 1.0
// DO NOT EDIT!!!

#include "inputdocument.h"


InputDocument::InputDocument(QObject* parent) : TelegramObject(parent)
{
	this->_id = 0;
	this->_access_hash = 0;
}

void InputDocument::read(MTProtoStream* mtstream) 
{
	this->_constructorid = mtstream->readTLConstructor();
	
	Q_ASSERT((this->_constructorid == InputDocument::ctorInputDocumentEmpty) ||
		 (this->_constructorid == InputDocument::ctorInputDocument));
	
	if(this->_constructorid == InputDocument::ctorInputDocument)
	{
		this->_id = mtstream->readTLLong();
		this->_access_hash = mtstream->readTLLong();
	}
}

void InputDocument::write(MTProtoStream* mtstream) 
{
	Q_ASSERT((this->_constructorid == InputDocument::ctorInputDocumentEmpty) ||
		 (this->_constructorid == InputDocument::ctorInputDocument));
	
	this->compileFlags();
	mtstream->writeTLConstructor(this->_constructorid);
	
	if(this->_constructorid == InputDocument::ctorInputDocument)
	{
		mtstream->writeTLLong(this->_id);
		mtstream->writeTLLong(this->_access_hash);
	}
}

void InputDocument::compileFlags() 
{
	
}

TLLong InputDocument::id() const
{
	return this->_id;
}

void InputDocument::setId(TLLong id) 
{
	if(this->_id == id)
		return;

	this->_id = id;
	emit idChanged();
}

TLLong InputDocument::accessHash() const
{
	return this->_access_hash;
}

void InputDocument::setAccessHash(TLLong access_hash) 
{
	if(this->_access_hash == access_hash)
		return;

	this->_access_hash = access_hash;
	emit accessHashChanged();
}

