#ifndef INPUTENCRYPTEDCHAT_H
#define INPUTENCRYPTEDCHAT_H

// Generated by APIGenerator 1.0
// DO NOT EDIT!!!

#include "../../types/telegramobject.h"
#include "../../types/basic.h"

class InputEncryptedChat: public TelegramObject
{
	Q_OBJECT

	Q_PROPERTY(TLInt chatId READ chatId WRITE setChatId NOTIFY chatIdChanged)
	Q_PROPERTY(TLLong accessHash READ accessHash WRITE setAccessHash NOTIFY accessHashChanged)

	Q_ENUMS(Constructors)

	public:
		enum Constructors {
			ctorInputEncryptedChat = 0xf141b5e1,
		};

	public:
		explicit InputEncryptedChat(QObject* parent = 0);
		virtual void read(MTProtoStream* mtstream);
		virtual void write(MTProtoStream* mtstream);
	protected:
		virtual void compileFlags();
	public:
		TLInt chatId() const;
		void setChatId(TLInt chat_id);
		TLLong accessHash() const;
		void setAccessHash(TLLong access_hash);

	signals:
		void chatIdChanged();
		void accessHashChanged();

	private:
		TLInt _chat_id;
		TLLong _access_hash;

};

#endif // INPUTENCRYPTEDCHAT_H
