// Generated by APIGenerator 1.0
// DO NOT EDIT!!!

#include "inputbotinlineresult.h"


InputBotInlineResult::InputBotInlineResult(QObject* parent) : TelegramObject(parent)
{
	this->_flags = 0;
	this->_w = 0;
	this->_h = 0;
	this->_duration = 0;
	this->_send_message = NULL;
	this->_photo = NULL;
	this->_document = NULL;
}

void InputBotInlineResult::read(MTProtoStream* mtstream) 
{
	this->_constructorid = mtstream->readTLConstructor();
	
	Q_ASSERT((this->_constructorid == InputBotInlineResult::CtorInputBotInlineResult) ||
		 (this->_constructorid == InputBotInlineResult::CtorInputBotInlineResultPhoto) ||
		 (this->_constructorid == InputBotInlineResult::CtorInputBotInlineResultDocument) ||
		 (this->_constructorid == InputBotInlineResult::CtorInputBotInlineResultGame));
	
	if(this->_constructorid == InputBotInlineResult::CtorInputBotInlineResult)
	{
		this->_flags = mtstream->readTLInt();
		this->_id = mtstream->readTLString();
		this->_type = mtstream->readTLString();
		if(IS_FLAG_SET(this->_flags, 1))
			this->_title = mtstream->readTLString();
		
		if(IS_FLAG_SET(this->_flags, 2))
			this->_description = mtstream->readTLString();
		
		if(IS_FLAG_SET(this->_flags, 3))
			this->_url = mtstream->readTLString();
		
		if(IS_FLAG_SET(this->_flags, 4))
			this->_thumb_url = mtstream->readTLString();
		
		if(IS_FLAG_SET(this->_flags, 5))
			this->_content_url = mtstream->readTLString();
		
		if(IS_FLAG_SET(this->_flags, 5))
			this->_content_type = mtstream->readTLString();
		
		if(IS_FLAG_SET(this->_flags, 6))
			this->_w = mtstream->readTLInt();
		
		if(IS_FLAG_SET(this->_flags, 6))
			this->_h = mtstream->readTLInt();
		
		if(IS_FLAG_SET(this->_flags, 7))
			this->_duration = mtstream->readTLInt();
		
		TLInt send_message_ctor = mtstream->peekTLConstructor();
		
		if(send_message_ctor != TLTypes::Null)
		{
			this->resetTLType<InputBotInlineMessage>(&this->_send_message);
			this->_send_message->read(mtstream);
		}
		else
		{
			this->nullTLType<InputBotInlineMessage>(&this->_send_message);
			mtstream->readTLConstructor(); // Skip Null
		}
	}
	else if(this->_constructorid == InputBotInlineResult::CtorInputBotInlineResultPhoto)
	{
		this->_id = mtstream->readTLString();
		this->_type = mtstream->readTLString();
		TLInt photo_ctor = mtstream->peekTLConstructor();
		
		if(photo_ctor != TLTypes::Null)
		{
			this->resetTLType<InputPhoto>(&this->_photo);
			this->_photo->read(mtstream);
		}
		else
		{
			this->nullTLType<InputPhoto>(&this->_photo);
			mtstream->readTLConstructor(); // Skip Null
		}
		
		TLInt send_message_ctor = mtstream->peekTLConstructor();
		
		if(send_message_ctor != TLTypes::Null)
		{
			this->resetTLType<InputBotInlineMessage>(&this->_send_message);
			this->_send_message->read(mtstream);
		}
		else
		{
			this->nullTLType<InputBotInlineMessage>(&this->_send_message);
			mtstream->readTLConstructor(); // Skip Null
		}
	}
	else if(this->_constructorid == InputBotInlineResult::CtorInputBotInlineResultDocument)
	{
		this->_flags = mtstream->readTLInt();
		this->_id = mtstream->readTLString();
		this->_type = mtstream->readTLString();
		if(IS_FLAG_SET(this->_flags, 1))
			this->_title = mtstream->readTLString();
		
		if(IS_FLAG_SET(this->_flags, 2))
			this->_description = mtstream->readTLString();
		
		TLInt document_ctor = mtstream->peekTLConstructor();
		
		if(document_ctor != TLTypes::Null)
		{
			this->resetTLType<InputDocument>(&this->_document);
			this->_document->read(mtstream);
		}
		else
		{
			this->nullTLType<InputDocument>(&this->_document);
			mtstream->readTLConstructor(); // Skip Null
		}
		
		TLInt send_message_ctor = mtstream->peekTLConstructor();
		
		if(send_message_ctor != TLTypes::Null)
		{
			this->resetTLType<InputBotInlineMessage>(&this->_send_message);
			this->_send_message->read(mtstream);
		}
		else
		{
			this->nullTLType<InputBotInlineMessage>(&this->_send_message);
			mtstream->readTLConstructor(); // Skip Null
		}
	}
	else if(this->_constructorid == InputBotInlineResult::CtorInputBotInlineResultGame)
	{
		this->_id = mtstream->readTLString();
		this->_short_name = mtstream->readTLString();
		TLInt send_message_ctor = mtstream->peekTLConstructor();
		
		if(send_message_ctor != TLTypes::Null)
		{
			this->resetTLType<InputBotInlineMessage>(&this->_send_message);
			this->_send_message->read(mtstream);
		}
		else
		{
			this->nullTLType<InputBotInlineMessage>(&this->_send_message);
			mtstream->readTLConstructor(); // Skip Null
		}
	}
}

void InputBotInlineResult::write(MTProtoStream* mtstream) 
{
	Q_ASSERT((this->_constructorid == InputBotInlineResult::CtorInputBotInlineResult) ||
		 (this->_constructorid == InputBotInlineResult::CtorInputBotInlineResultPhoto) ||
		 (this->_constructorid == InputBotInlineResult::CtorInputBotInlineResultDocument) ||
		 (this->_constructorid == InputBotInlineResult::CtorInputBotInlineResultGame));
	
	this->compileFlags();
	mtstream->writeTLConstructor(this->_constructorid);
	
	if(this->_constructorid == InputBotInlineResult::CtorInputBotInlineResult)
	{
		mtstream->writeTLInt(this->_flags);
		mtstream->writeTLString(this->_id);
		mtstream->writeTLString(this->_type);
		if(IS_FLAG_SET(this->_flags, 1))
			mtstream->writeTLString(this->_title);
		
		if(IS_FLAG_SET(this->_flags, 2))
			mtstream->writeTLString(this->_description);
		
		if(IS_FLAG_SET(this->_flags, 3))
			mtstream->writeTLString(this->_url);
		
		if(IS_FLAG_SET(this->_flags, 4))
			mtstream->writeTLString(this->_thumb_url);
		
		if(IS_FLAG_SET(this->_flags, 5))
			mtstream->writeTLString(this->_content_url);
		
		if(IS_FLAG_SET(this->_flags, 5))
			mtstream->writeTLString(this->_content_type);
		
		if(IS_FLAG_SET(this->_flags, 6))
			mtstream->writeTLInt(this->_w);
		
		if(IS_FLAG_SET(this->_flags, 6))
			mtstream->writeTLInt(this->_h);
		
		if(IS_FLAG_SET(this->_flags, 7))
			mtstream->writeTLInt(this->_duration);
		
		if(this->_send_message != NULL)
			this->_send_message->write(mtstream);
		else
			mtstream->writeTLConstructor(TLTypes::Null);
	}
	else if(this->_constructorid == InputBotInlineResult::CtorInputBotInlineResultPhoto)
	{
		mtstream->writeTLString(this->_id);
		mtstream->writeTLString(this->_type);
		if(this->_photo != NULL)
			this->_photo->write(mtstream);
		else
			mtstream->writeTLConstructor(TLTypes::Null);
		
		if(this->_send_message != NULL)
			this->_send_message->write(mtstream);
		else
			mtstream->writeTLConstructor(TLTypes::Null);
	}
	else if(this->_constructorid == InputBotInlineResult::CtorInputBotInlineResultDocument)
	{
		mtstream->writeTLInt(this->_flags);
		mtstream->writeTLString(this->_id);
		mtstream->writeTLString(this->_type);
		if(IS_FLAG_SET(this->_flags, 1))
			mtstream->writeTLString(this->_title);
		
		if(IS_FLAG_SET(this->_flags, 2))
			mtstream->writeTLString(this->_description);
		
		if(this->_document != NULL)
			this->_document->write(mtstream);
		else
			mtstream->writeTLConstructor(TLTypes::Null);
		
		if(this->_send_message != NULL)
			this->_send_message->write(mtstream);
		else
			mtstream->writeTLConstructor(TLTypes::Null);
	}
	else if(this->_constructorid == InputBotInlineResult::CtorInputBotInlineResultGame)
	{
		mtstream->writeTLString(this->_id);
		mtstream->writeTLString(this->_short_name);
		if(this->_send_message != NULL)
			this->_send_message->write(mtstream);
		else
			mtstream->writeTLConstructor(TLTypes::Null);
	}
}

void InputBotInlineResult::compileFlags() 
{
	this->_flags = 0;
	
	if(this->_constructorid == InputBotInlineResult::CtorInputBotInlineResult)
	{
		if(!this->_title.isEmpty())
			SET_FLAG_BIT(this->_flags, 1);
		if(!this->_description.isEmpty())
			SET_FLAG_BIT(this->_flags, 2);
		if(!this->_url.isEmpty())
			SET_FLAG_BIT(this->_flags, 3);
		if(!this->_thumb_url.isEmpty())
			SET_FLAG_BIT(this->_flags, 4);
		if(!this->_content_url.isEmpty())
			SET_FLAG_BIT(this->_flags, 5);
		if(!this->_content_type.isEmpty())
			SET_FLAG_BIT(this->_flags, 5);
		if(this->_w)
			SET_FLAG_BIT(this->_flags, 6);
		if(this->_h)
			SET_FLAG_BIT(this->_flags, 6);
		if(this->_duration)
			SET_FLAG_BIT(this->_flags, 7);
	}
	else if(this->_constructorid == InputBotInlineResult::CtorInputBotInlineResultDocument)
	{
		if(!this->_title.isEmpty())
			SET_FLAG_BIT(this->_flags, 1);
		if(!this->_description.isEmpty())
			SET_FLAG_BIT(this->_flags, 2);
	}
}

TLInt InputBotInlineResult::flags() const
{
	return this->_flags;
}

void InputBotInlineResult::setFlags(TLInt flags) 
{
	if(this->_flags == flags)
		return;

	this->_flags = flags;
	emit flagsChanged();
}

TLString InputBotInlineResult::id() const
{
	return this->_id;
}

void InputBotInlineResult::setId(TLString id) 
{
	if(this->_id == id)
		return;

	this->_id = id;
	emit idChanged();
}

TLString InputBotInlineResult::type() const
{
	return this->_type;
}

void InputBotInlineResult::setType(TLString type) 
{
	if(this->_type == type)
		return;

	this->_type = type;
	emit typeChanged();
}

TLString InputBotInlineResult::title() const
{
	return this->_title;
}

void InputBotInlineResult::setTitle(TLString title) 
{
	if(this->_title == title)
		return;

	this->_title = title;
	emit titleChanged();
}

TLString InputBotInlineResult::description() const
{
	return this->_description;
}

void InputBotInlineResult::setDescription(TLString description) 
{
	if(this->_description == description)
		return;

	this->_description = description;
	emit descriptionChanged();
}

TLString InputBotInlineResult::url() const
{
	return this->_url;
}

void InputBotInlineResult::setUrl(TLString url) 
{
	if(this->_url == url)
		return;

	this->_url = url;
	emit urlChanged();
}

TLString InputBotInlineResult::thumbUrl() const
{
	return this->_thumb_url;
}

void InputBotInlineResult::setThumbUrl(TLString thumb_url) 
{
	if(this->_thumb_url == thumb_url)
		return;

	this->_thumb_url = thumb_url;
	emit thumbUrlChanged();
}

TLString InputBotInlineResult::contentUrl() const
{
	return this->_content_url;
}

void InputBotInlineResult::setContentUrl(TLString content_url) 
{
	if(this->_content_url == content_url)
		return;

	this->_content_url = content_url;
	emit contentUrlChanged();
}

TLString InputBotInlineResult::contentType() const
{
	return this->_content_type;
}

void InputBotInlineResult::setContentType(TLString content_type) 
{
	if(this->_content_type == content_type)
		return;

	this->_content_type = content_type;
	emit contentTypeChanged();
}

TLInt InputBotInlineResult::w() const
{
	return this->_w;
}

void InputBotInlineResult::setW(TLInt w) 
{
	if(this->_w == w)
		return;

	this->_w = w;
	emit wChanged();
}

TLInt InputBotInlineResult::h() const
{
	return this->_h;
}

void InputBotInlineResult::setH(TLInt h) 
{
	if(this->_h == h)
		return;

	this->_h = h;
	emit hChanged();
}

TLInt InputBotInlineResult::duration() const
{
	return this->_duration;
}

void InputBotInlineResult::setDuration(TLInt duration) 
{
	if(this->_duration == duration)
		return;

	this->_duration = duration;
	emit durationChanged();
}

InputBotInlineMessage* InputBotInlineResult::sendMessage() const
{
	return this->_send_message;
}

void InputBotInlineResult::setSendMessage(InputBotInlineMessage* send_message) 
{
	if(this->_send_message == send_message)
		return;

	this->deleteChild(this->_send_message);
	this->_send_message = send_message;

	if(this->_send_message)
		this->_send_message->setParent(this);

	emit sendMessageChanged();
}

InputPhoto* InputBotInlineResult::photo() const
{
	return this->_photo;
}

void InputBotInlineResult::setPhoto(InputPhoto* photo) 
{
	if(this->_photo == photo)
		return;

	this->deleteChild(this->_photo);
	this->_photo = photo;

	if(this->_photo)
		this->_photo->setParent(this);

	emit photoChanged();
}

InputDocument* InputBotInlineResult::document() const
{
	return this->_document;
}

void InputBotInlineResult::setDocument(InputDocument* document) 
{
	if(this->_document == document)
		return;

	this->deleteChild(this->_document);
	this->_document = document;

	if(this->_document)
		this->_document->setParent(this);

	emit documentChanged();
}

TLString InputBotInlineResult::shortName() const
{
	return this->_short_name;
}

void InputBotInlineResult::setShortName(TLString short_name) 
{
	if(this->_short_name == short_name)
		return;

	this->_short_name = short_name;
	emit shortNameChanged();
}

