// Generated by APIGenerator 1.0
// DO NOT EDIT!!!

#include "inputprivacykey.h"

InputPrivacyKey::InputPrivacyKey(QObject* parent) : TelegramObject(parent)
{
	
}

void InputPrivacyKey::read(MTProtoStream* mtstream) 
{
	this->_constructorid = mtstream->readTLConstructor();
	
	Q_ASSERT((this->_constructorid == InputPrivacyKey::CtorInputPrivacyKeyStatusTimestamp) ||
		 (this->_constructorid == InputPrivacyKey::CtorInputPrivacyKeyChatInvite));
}

void InputPrivacyKey::write(MTProtoStream* mtstream) 
{
	Q_ASSERT((this->_constructorid == InputPrivacyKey::CtorInputPrivacyKeyStatusTimestamp) ||
		 (this->_constructorid == InputPrivacyKey::CtorInputPrivacyKeyChatInvite));
	
	this->compileFlags();
	mtstream->writeTLConstructor(this->_constructorid);
}

void InputPrivacyKey::compileFlags() 
{
	
}

