#ifndef INPUTCHATPHOTO_H
#define INPUTCHATPHOTO_H

// Generated by APIGenerator 1.0
// DO NOT EDIT!!!

#include "../../types/telegramobject.h"
#include "../../types/basic.h"
#include "inputphoto.h"
#include "inputfile.h"

class InputChatPhoto: public TelegramObject
{
	Q_OBJECT

	Q_PROPERTY(InputFile* file READ file WRITE setFile NOTIFY fileChanged)
	Q_PROPERTY(InputPhoto* id READ id WRITE setId NOTIFY idChanged)

	Q_ENUMS(Constructors)

	public:
		enum Constructors {
			ctorInputChatPhotoEmpty = 0x1ca48f57,
			ctorInputChatUploadedPhoto = 0x927c55b4,
			ctorInputChatPhoto = 0x8953ad37,
		};

	public:
		explicit InputChatPhoto(QObject* parent = 0);
		virtual void read(MTProtoStream* mtstream);
		virtual void write(MTProtoStream* mtstream);
	protected:
		virtual void compileFlags();
	public:
		InputFile* file() const;
		void setFile(InputFile* file);
		InputPhoto* id() const;
		void setId(InputPhoto* id);

	signals:
		void fileChanged();
		void idChanged();

	private:
		InputFile* _file;
		InputPhoto* _id;

};

#endif // INPUTCHATPHOTO_H
