#ifndef INPUTPEERNOTIFYEVENTS_H
#define INPUTPEERNOTIFYEVENTS_H

// Generated by APIGenerator 1.0
// DO NOT EDIT!!!

#include "../../types/telegramobject.h"
#include "../../types/basic.h"

class InputPeerNotifyEvents: public TelegramObject
{
	Q_OBJECT

	Q_ENUMS(Constructors)

	public:
		enum Constructors {
			ctorInputPeerNotifyEventsEmpty = 0xf03064d8,
			ctorInputPeerNotifyEventsAll = 0xe86a2c74,
		};

	public:
		explicit InputPeerNotifyEvents(QObject* parent = 0);
		virtual void read(MTProtoStream* mtstream);
		virtual void write(MTProtoStream* mtstream);
	protected:
		virtual void compileFlags();

};

#endif // INPUTPEERNOTIFYEVENTS_H
