#ifndef INPUTPHOTO_H
#define INPUTPHOTO_H

// Generated by APIGenerator 1.0
// DO NOT EDIT!!!

#include "../../types/telegramobject.h"
#include "../../types/basic.h"

class InputPhoto: public TelegramObject
{
	Q_OBJECT

	Q_PROPERTY(TLLong id READ id WRITE setId NOTIFY idChanged)
	Q_PROPERTY(TLLong accessHash READ accessHash WRITE setAccessHash NOTIFY accessHashChanged)

	Q_ENUMS(Constructors)

	public:
		enum Constructors {
			ctorInputPhotoEmpty = 0x1cd7bf0d,
			ctorInputPhoto = 0xfb95c6c4,
		};

	public:
		explicit InputPhoto(QObject* parent = 0);
		virtual void read(MTProtoStream* mtstream);
		virtual void write(MTProtoStream* mtstream);
	protected:
		virtual void compileFlags();
	public:
		TLLong id() const;
		void setId(TLLong id);
		TLLong accessHash() const;
		void setAccessHash(TLLong access_hash);

	signals:
		void idChanged();
		void accessHashChanged();

	private:
		TLLong _id;
		TLLong _access_hash;

};

#endif // INPUTPHOTO_H
