#ifndef MASKCOORDS_H
#define MASKCOORDS_H

// Generated by APIGenerator 1.0
// DO NOT EDIT!!!

#include "../../types/telegramobject.h"
#include "../../types/basic.h"

class MaskCoords: public TelegramObject
{
	Q_OBJECT

	Q_PROPERTY(TLInt n READ n WRITE setN NOTIFY nChanged)
	Q_PROPERTY(TLDouble x READ x WRITE setX NOTIFY xChanged)
	Q_PROPERTY(TLDouble y READ y WRITE setY NOTIFY yChanged)
	Q_PROPERTY(TLDouble zoom READ zoom WRITE setZoom NOTIFY zoomChanged)

	Q_ENUMS(Constructors)

	public:
		enum Constructors {
			CtorMaskCoords = 0xaed6dbb2,
		};

	public:
		explicit MaskCoords(QObject* parent = 0);
		virtual void read(MTProtoStream* mtstream);
		virtual void write(MTProtoStream* mtstream);
	protected:
		virtual void compileFlags();
	public:
		TLInt n() const;
		void setN(TLInt n);
		TLDouble x() const;
		void setX(TLDouble x);
		TLDouble y() const;
		void setY(TLDouble y);
		TLDouble zoom() const;
		void setZoom(TLDouble zoom);

	signals:
		void nChanged();
		void xChanged();
		void yChanged();
		void zoomChanged();

	private:
		TLInt _n;
		TLDouble _x;
		TLDouble _y;
		TLDouble _zoom;

};

#endif // MASKCOORDS_H
