#ifndef MESSAGESMESSAGEEDITDATA_H
#define MESSAGESMESSAGEEDITDATA_H

// Generated by APIGenerator 1.0
// DO NOT EDIT!!!

#include "../../types/telegramobject.h"
#include "../../types/basic.h"

class MessagesMessageEditData: public TelegramObject
{
	Q_OBJECT

	Q_PROPERTY(TLInt flags READ flags WRITE setFlags NOTIFY flagsChanged)
	Q_PROPERTY(TLTrue isCaption READ isCaption WRITE setIsCaption NOTIFY isCaptionChanged)

	Q_ENUMS(Constructors)

	public:
		enum Constructors {
			CtorMessagesMessageEditData = 0x26b5dde6,
		};

	public:
		explicit MessagesMessageEditData(QObject* parent = 0);
		virtual void read(MTProtoStream* mtstream);
		virtual void write(MTProtoStream* mtstream);
	protected:
		virtual void compileFlags();
	public:
		TLInt flags() const;
		void setFlags(TLInt flags);
		TLTrue isCaption() const;
		void setIsCaption(TLTrue is_caption);

	signals:
		void flagsChanged();
		void isCaptionChanged();

	private:
		TLInt _flags;
		TLTrue _is_caption;

};

#endif // MESSAGESMESSAGEEDITDATA_H
