// Generated by APIGenerator 1.0
// DO NOT EDIT!!!

#include "messagesmessageeditdata.h"


MessagesMessageEditData::MessagesMessageEditData(QObject* parent) : TelegramObject(parent)
{
	this->_flags = 0;
	this->_is_caption = false;
	this->_constructorid = MessagesMessageEditData::CtorMessagesMessageEditData;
}

void MessagesMessageEditData::read(MTProtoStream* mtstream) 
{
	this->_constructorid = mtstream->readTLConstructor();
	
	Q_ASSERT((this->_constructorid == MessagesMessageEditData::CtorMessagesMessageEditData));
	
	if(this->_constructorid == MessagesMessageEditData::CtorMessagesMessageEditData)
	{
		this->_flags = mtstream->readTLInt();
		this->_is_caption = IS_FLAG_SET(this->_flags, 0);
	}
}

void MessagesMessageEditData::write(MTProtoStream* mtstream) 
{
	Q_ASSERT((this->_constructorid == MessagesMessageEditData::CtorMessagesMessageEditData));
	
	this->compileFlags();
	mtstream->writeTLConstructor(this->_constructorid);
	
	if(this->_constructorid == MessagesMessageEditData::CtorMessagesMessageEditData)
		mtstream->writeTLInt(this->_flags);
}

void MessagesMessageEditData::compileFlags() 
{
	this->_flags = 0;
	
	if(this->_constructorid == MessagesMessageEditData::CtorMessagesMessageEditData)
	{
		if(this->_is_caption)
			SET_FLAG_BIT(this->_flags, 0);
	}
}

TLInt MessagesMessageEditData::flags() const
{
	return this->_flags;
}

void MessagesMessageEditData::setFlags(TLInt flags) 
{
	if(this->_flags == flags)
		return;

	this->_flags = flags;
	emit flagsChanged();
}

TLTrue MessagesMessageEditData::isCaption() const
{
	return this->_is_caption;
}

void MessagesMessageEditData::setIsCaption(TLTrue is_caption) 
{
	if(this->_is_caption == is_caption)
		return;

	this->_is_caption = is_caption;
	emit isCaptionChanged();
}

