#ifndef MESSAGESAFFECTEDHISTORY_H
#define MESSAGESAFFECTEDHISTORY_H

// Generated by APIGenerator 1.0
// DO NOT EDIT!!!

#include "../../types/basic.h"
#include "../../types/telegramobject.h"

class MessagesAffectedHistory: public TelegramObject
{
	Q_OBJECT

	Q_PROPERTY(TLInt pts READ pts WRITE setPts NOTIFY ptsChanged)
	Q_PROPERTY(TLInt ptsCount READ ptsCount WRITE setPtsCount NOTIFY ptsCountChanged)
	Q_PROPERTY(TLInt offset READ offset WRITE setOffset NOTIFY offsetChanged)

	Q_ENUMS(Constructors)

	public:
		enum Constructors {
			CtorMessagesAffectedHistory = 0xb45c69d1,
		};

	public:
		explicit MessagesAffectedHistory(QObject* parent = 0);
		virtual void read(MTProtoStream* mtstream);
		virtual void write(MTProtoStream* mtstream);
	protected:
		virtual void compileFlags();
	public:
		TLInt pts() const;
		void setPts(TLInt pts);
		TLInt ptsCount() const;
		void setPtsCount(TLInt pts_count);
		TLInt offset() const;
		void setOffset(TLInt offset);

	signals:
		void ptsChanged();
		void ptsCountChanged();
		void offsetChanged();

	private:
		TLInt _pts;
		TLInt _pts_count;
		TLInt _offset;

};

#endif // MESSAGESAFFECTEDHISTORY_H
