#ifndef MESSAGESDIALOGS_H
#define MESSAGESDIALOGS_H

// Generated by APIGenerator 1.0
// DO NOT EDIT!!!

#include "message.h"
#include "user.h"
#include "../../types/basic.h"
#include "dialog.h"
#include "../../types/telegramobject.h"
#include "chat.h"

class MessagesDialogs: public TelegramObject
{
	Q_OBJECT

	Q_PROPERTY(TLVector<Dialog*> dialogs READ dialogs WRITE setDialogs NOTIFY dialogsChanged)
	Q_PROPERTY(TLVector<Message*> messages READ messages WRITE setMessages NOTIFY messagesChanged)
	Q_PROPERTY(TLVector<Chat*> chats READ chats WRITE setChats NOTIFY chatsChanged)
	Q_PROPERTY(TLVector<User*> users READ users WRITE setUsers NOTIFY usersChanged)
	Q_PROPERTY(TLInt count READ count WRITE setCount NOTIFY countChanged)

	public:
		enum Constructors {
			ctorMessagesDialogs = 0x15ba6c40,
			ctorMessagesDialogsSlice = 0x71e094f3,
		};

	public:
		explicit MessagesDialogs(QObject* parent = 0);
		virtual void read(MTProtoStream* mtstream);
		virtual void write(MTProtoStream* mtstream);
	protected:
		virtual void compileFlags();
	public:
		const TLVector<Dialog*>& dialogs() const;
		void setDialogs(const TLVector<Dialog*>& dialogs);
		const TLVector<Message*>& messages() const;
		void setMessages(const TLVector<Message*>& messages);
		const TLVector<Chat*>& chats() const;
		void setChats(const TLVector<Chat*>& chats);
		const TLVector<User*>& users() const;
		void setUsers(const TLVector<User*>& users);
		TLInt count() const;
		void setCount(TLInt count);

	signals:
		void dialogsChanged();
		void messagesChanged();
		void chatsChanged();
		void usersChanged();
		void countChanged();

	private:
		TLVector<Dialog*> _dialogs;
		TLVector<Message*> _messages;
		TLVector<Chat*> _chats;
		TLVector<User*> _users;
		TLInt _count;

};

#endif // MESSAGESDIALOGS_H
