#ifndef MESSAGESFILTER_H
#define MESSAGESFILTER_H

// Generated by APIGenerator 1.0
// DO NOT EDIT!!!

#include "../../types/telegramobject.h"
#include "../../types/basic.h"

class MessagesFilter: public TelegramObject
{
	Q_OBJECT

	Q_ENUMS(Constructors)

	public:
		enum Constructors {
			ctorInputMessagesFilterEmpty = 0x57e2f66c,
			ctorInputMessagesFilterPhotos = 0x9609a51c,
			ctorInputMessagesFilterVideo = 0x9fc00e65,
			ctorInputMessagesFilterPhotoVideo = 0x56e9f0e4,
			ctorInputMessagesFilterPhotoVideoDocuments = 0xd95e73bb,
			ctorInputMessagesFilterDocument = 0x9eddf188,
			ctorInputMessagesFilterUrl = 0x7ef0dd87,
			ctorInputMessagesFilterGif = 0xffc86587,
			ctorInputMessagesFilterVoice = 0x50f5c392,
			ctorInputMessagesFilterMusic = 0x3751b49e,
			ctorInputMessagesFilterChatPhotos = 0x3a20ecb8,
		};

	public:
		explicit MessagesFilter(QObject* parent = 0);
		virtual void read(MTProtoStream* mtstream);
		virtual void write(MTProtoStream* mtstream);
	protected:
		virtual void compileFlags();

};

#endif // MESSAGESFILTER_H
