#ifndef NOTIFYPEER_H
#define NOTIFYPEER_H

// Generated by APIGenerator 1.0
// DO NOT EDIT!!!

#include "../../types/basic.h"
#include "../../types/telegramobject.h"
#include "peer.h"

class NotifyPeer: public TelegramObject
{
	Q_OBJECT

	Q_PROPERTY(Peer* peer READ peer WRITE setPeer NOTIFY peerChanged)

	Q_ENUMS(Constructors)

	public:
		enum Constructors {
			CtorNotifyPeer = 0x9fd40bd8,
			CtorNotifyUsers = 0xb4c83b4c,
			CtorNotifyChats = 0xc007cec3,
			CtorNotifyAll = 0x74d07c60,
		};

	public:
		explicit NotifyPeer(QObject* parent = 0);
		virtual void read(MTProtoStream* mtstream);
		virtual void write(MTProtoStream* mtstream);
	protected:
		virtual void compileFlags();
	public:
		Peer* peer() const;
		void setPeer(Peer* peer);

	signals:
		void peerChanged();

	private:
		Peer* _peer;

};

#endif // NOTIFYPEER_H
