#ifndef PEERNOTIFYEVENTS_H
#define PEERNOTIFYEVENTS_H

// Generated by APIGenerator 1.0
// DO NOT EDIT!!!

#include "../../types/basic.h"
#include "../../types/telegramobject.h"

class PeerNotifyEvents: public TelegramObject
{
	Q_OBJECT

	Q_ENUMS(Constructors)

	public:
		enum Constructors {
			CtorPeerNotifyEventsEmpty = 0xadd53cb3,
			CtorPeerNotifyEventsAll = 0x6d1ded88,
		};

	public:
		explicit PeerNotifyEvents(QObject* parent = 0);
		virtual void read(MTProtoStream* mtstream);
		virtual void write(MTProtoStream* mtstream);
	protected:
		virtual void compileFlags();

};

#endif // PEERNOTIFYEVENTS_H
