#ifndef PEERSETTINGS_H
#define PEERSETTINGS_H

// Generated by APIGenerator 1.0
// DO NOT EDIT!!!

#include "../../types/basic.h"
#include "../../types/telegramobject.h"

class PeerSettings: public TelegramObject
{
	Q_OBJECT

	Q_PROPERTY(TLInt flags READ flags WRITE setFlags NOTIFY flagsChanged)
	Q_PROPERTY(TLTrue isReportSpam READ isReportSpam WRITE setIsReportSpam NOTIFY isReportSpamChanged)

	Q_ENUMS(Constructors)

	public:
		enum Constructors {
			CtorPeerSettings = 0x818426cd,
		};

	public:
		explicit PeerSettings(QObject* parent = 0);
		virtual void read(MTProtoStream* mtstream);
		virtual void write(MTProtoStream* mtstream);
	protected:
		virtual void compileFlags();
	public:
		TLInt flags() const;
		void setFlags(TLInt flags);
		TLTrue isReportSpam() const;
		void setIsReportSpam(TLTrue is_report_spam);

	signals:
		void flagsChanged();
		void isReportSpamChanged();

	private:
		TLInt _flags;
		TLTrue _is_report_spam;

};

#endif // PEERSETTINGS_H
