#ifndef PRIVACYRULE_H
#define PRIVACYRULE_H

// Generated by APIGenerator 1.0
// DO NOT EDIT!!!

#include "../../types/telegramobject.h"
#include "../../types/basic.h"

class PrivacyRule: public TelegramObject
{
	Q_OBJECT

	Q_PROPERTY(TLVector<TLInt> users READ users WRITE setUsers NOTIFY usersChanged)

	Q_ENUMS(Constructors)

	public:
		enum Constructors {
			ctorPrivacyValueAllowContacts = 0xfffe1bac,
			ctorPrivacyValueAllowAll = 0x65427b82,
			ctorPrivacyValueAllowUsers = 0x4d5bbe0c,
			ctorPrivacyValueDisallowContacts = 0xf888fa1a,
			ctorPrivacyValueDisallowAll = 0x8b73e763,
			ctorPrivacyValueDisallowUsers = 0xc7f49b7,
		};

	public:
		explicit PrivacyRule(QObject* parent = 0);
		virtual void read(MTProtoStream* mtstream);
		virtual void write(MTProtoStream* mtstream);
	protected:
		virtual void compileFlags();
	public:
		const TLVector<TLInt>& users() const;
		void setUsers(const TLVector<TLInt>& users);

	signals:
		void usersChanged();

	private:
		TLVector<TLInt> _users;

};

#endif // PRIVACYRULE_H
