// Generated by APIGenerator 1.0
// DO NOT EDIT!!!

#include "reportreason.h"


ReportReason::ReportReason(QObject* parent) : TelegramObject(parent)
{
	
}

void ReportReason::read(MTProtoStream* mtstream) 
{
	this->_constructorid = mtstream->readTLConstructor();
	
	Q_ASSERT((this->_constructorid == ReportReason::CtorInputReportReasonSpam) ||
		 (this->_constructorid == ReportReason::CtorInputReportReasonViolence) ||
		 (this->_constructorid == ReportReason::CtorInputReportReasonPornography) ||
		 (this->_constructorid == ReportReason::CtorInputReportReasonOther));
	
	if(this->_constructorid == ReportReason::CtorInputReportReasonOther)
		this->_text = mtstream->readTLString();
}

void ReportReason::write(MTProtoStream* mtstream) 
{
	Q_ASSERT((this->_constructorid == ReportReason::CtorInputReportReasonSpam) ||
		 (this->_constructorid == ReportReason::CtorInputReportReasonViolence) ||
		 (this->_constructorid == ReportReason::CtorInputReportReasonPornography) ||
		 (this->_constructorid == ReportReason::CtorInputReportReasonOther));
	
	this->compileFlags();
	mtstream->writeTLConstructor(this->_constructorid);
	
	if(this->_constructorid == ReportReason::CtorInputReportReasonOther)
		mtstream->writeTLString(this->_text);
}

void ReportReason::compileFlags() 
{
	
}

TLString ReportReason::text() const
{
	return this->_text;
}

void ReportReason::setText(TLString text) 
{
	if(this->_text == text)
		return;

	this->_text = text;
	emit textChanged();
}

