// Generated by APIGenerator 1.0
// DO NOT EDIT!!!

#include "sendmessageaction.h"


SendMessageAction::SendMessageAction(QObject* parent) : TelegramObject(parent)
{
	this->_progress = 0;
}

void SendMessageAction::read(MTProtoStream* mtstream) 
{
	this->_constructorid = mtstream->readTLConstructor();
	
	Q_ASSERT((this->_constructorid == SendMessageAction::CtorSendMessageTypingAction) ||
		 (this->_constructorid == SendMessageAction::CtorSendMessageCancelAction) ||
		 (this->_constructorid == SendMessageAction::CtorSendMessageRecordVideoAction) ||
		 (this->_constructorid == SendMessageAction::CtorSendMessageUploadVideoAction) ||
		 (this->_constructorid == SendMessageAction::CtorSendMessageRecordAudioAction) ||
		 (this->_constructorid == SendMessageAction::CtorSendMessageUploadAudioAction) ||
		 (this->_constructorid == SendMessageAction::CtorSendMessageUploadPhotoAction) ||
		 (this->_constructorid == SendMessageAction::CtorSendMessageUploadDocumentAction) ||
		 (this->_constructorid == SendMessageAction::CtorSendMessageGeoLocationAction) ||
		 (this->_constructorid == SendMessageAction::CtorSendMessageChooseContactAction) ||
		 (this->_constructorid == SendMessageAction::CtorSendMessageGamePlayAction) ||
		 (this->_constructorid == SendMessageAction::CtorSendMessageGameStopAction));
	
	if(this->_constructorid == SendMessageAction::CtorSendMessageUploadVideoAction)
		this->_progress = mtstream->readTLInt();
	else if(this->_constructorid == SendMessageAction::CtorSendMessageUploadAudioAction)
		this->_progress = mtstream->readTLInt();
	else if(this->_constructorid == SendMessageAction::CtorSendMessageUploadPhotoAction)
		this->_progress = mtstream->readTLInt();
	else if(this->_constructorid == SendMessageAction::CtorSendMessageUploadDocumentAction)
		this->_progress = mtstream->readTLInt();
}

void SendMessageAction::write(MTProtoStream* mtstream) 
{
	Q_ASSERT((this->_constructorid == SendMessageAction::CtorSendMessageTypingAction) ||
		 (this->_constructorid == SendMessageAction::CtorSendMessageCancelAction) ||
		 (this->_constructorid == SendMessageAction::CtorSendMessageRecordVideoAction) ||
		 (this->_constructorid == SendMessageAction::CtorSendMessageUploadVideoAction) ||
		 (this->_constructorid == SendMessageAction::CtorSendMessageRecordAudioAction) ||
		 (this->_constructorid == SendMessageAction::CtorSendMessageUploadAudioAction) ||
		 (this->_constructorid == SendMessageAction::CtorSendMessageUploadPhotoAction) ||
		 (this->_constructorid == SendMessageAction::CtorSendMessageUploadDocumentAction) ||
		 (this->_constructorid == SendMessageAction::CtorSendMessageGeoLocationAction) ||
		 (this->_constructorid == SendMessageAction::CtorSendMessageChooseContactAction) ||
		 (this->_constructorid == SendMessageAction::CtorSendMessageGamePlayAction) ||
		 (this->_constructorid == SendMessageAction::CtorSendMessageGameStopAction));
	
	this->compileFlags();
	mtstream->writeTLConstructor(this->_constructorid);
	
	if(this->_constructorid == SendMessageAction::CtorSendMessageUploadVideoAction)
		mtstream->writeTLInt(this->_progress);
	else if(this->_constructorid == SendMessageAction::CtorSendMessageUploadAudioAction)
		mtstream->writeTLInt(this->_progress);
	else if(this->_constructorid == SendMessageAction::CtorSendMessageUploadPhotoAction)
		mtstream->writeTLInt(this->_progress);
	else if(this->_constructorid == SendMessageAction::CtorSendMessageUploadDocumentAction)
		mtstream->writeTLInt(this->_progress);
}

void SendMessageAction::compileFlags() 
{
	
}

TLInt SendMessageAction::progress() const
{
	return this->_progress;
}

void SendMessageAction::setProgress(TLInt progress) 
{
	if(this->_progress == progress)
		return;

	this->_progress = progress;
	emit progressChanged();
}

