// Generated by APIGenerator 1.0
// DO NOT EDIT!!!

#include "sendmessageaction.h"


SendMessageAction::SendMessageAction(QObject* parent) : TelegramObject(parent)
{
	this->_progress = 0;
}

void SendMessageAction::read(MTProtoStream* mtstream) 
{
	this->_constructorid = mtstream->readTLConstructor();
	
	Q_ASSERT((this->_constructorid == SendMessageAction::ctorSendMessageTypingAction) ||
		 (this->_constructorid == SendMessageAction::ctorSendMessageCancelAction) ||
		 (this->_constructorid == SendMessageAction::ctorSendMessageRecordVideoAction) ||
		 (this->_constructorid == SendMessageAction::ctorSendMessageUploadVideoAction) ||
		 (this->_constructorid == SendMessageAction::ctorSendMessageRecordAudioAction) ||
		 (this->_constructorid == SendMessageAction::ctorSendMessageUploadAudioAction) ||
		 (this->_constructorid == SendMessageAction::ctorSendMessageUploadPhotoAction) ||
		 (this->_constructorid == SendMessageAction::ctorSendMessageUploadDocumentAction) ||
		 (this->_constructorid == SendMessageAction::ctorSendMessageGeoLocationAction) ||
		 (this->_constructorid == SendMessageAction::ctorSendMessageChooseContactAction) ||
		 (this->_constructorid == SendMessageAction::ctorSendMessageGamePlayAction) ||
		 (this->_constructorid == SendMessageAction::ctorSendMessageGameStopAction));
	
	if(this->_constructorid == SendMessageAction::ctorSendMessageUploadVideoAction)
		this->_progress = mtstream->readTLInt();
	else if(this->_constructorid == SendMessageAction::ctorSendMessageUploadAudioAction)
		this->_progress = mtstream->readTLInt();
	else if(this->_constructorid == SendMessageAction::ctorSendMessageUploadPhotoAction)
		this->_progress = mtstream->readTLInt();
	else if(this->_constructorid == SendMessageAction::ctorSendMessageUploadDocumentAction)
		this->_progress = mtstream->readTLInt();
}

void SendMessageAction::write(MTProtoStream* mtstream) 
{
	Q_ASSERT((this->_constructorid == SendMessageAction::ctorSendMessageTypingAction) ||
		 (this->_constructorid == SendMessageAction::ctorSendMessageCancelAction) ||
		 (this->_constructorid == SendMessageAction::ctorSendMessageRecordVideoAction) ||
		 (this->_constructorid == SendMessageAction::ctorSendMessageUploadVideoAction) ||
		 (this->_constructorid == SendMessageAction::ctorSendMessageRecordAudioAction) ||
		 (this->_constructorid == SendMessageAction::ctorSendMessageUploadAudioAction) ||
		 (this->_constructorid == SendMessageAction::ctorSendMessageUploadPhotoAction) ||
		 (this->_constructorid == SendMessageAction::ctorSendMessageUploadDocumentAction) ||
		 (this->_constructorid == SendMessageAction::ctorSendMessageGeoLocationAction) ||
		 (this->_constructorid == SendMessageAction::ctorSendMessageChooseContactAction) ||
		 (this->_constructorid == SendMessageAction::ctorSendMessageGamePlayAction) ||
		 (this->_constructorid == SendMessageAction::ctorSendMessageGameStopAction));
	
	this->compileFlags();
	mtstream->writeTLConstructor(this->_constructorid);
	
	if(this->_constructorid == SendMessageAction::ctorSendMessageUploadVideoAction)
		mtstream->writeTLInt(this->_progress);
	else if(this->_constructorid == SendMessageAction::ctorSendMessageUploadAudioAction)
		mtstream->writeTLInt(this->_progress);
	else if(this->_constructorid == SendMessageAction::ctorSendMessageUploadPhotoAction)
		mtstream->writeTLInt(this->_progress);
	else if(this->_constructorid == SendMessageAction::ctorSendMessageUploadDocumentAction)
		mtstream->writeTLInt(this->_progress);
}

void SendMessageAction::compileFlags() 
{
	
}

TLInt SendMessageAction::progress() const
{
	return this->_progress;
}

void SendMessageAction::setProgress(TLInt progress) 
{
	if(this->_progress == progress)
		return;

	this->_progress = progress;
	emit progressChanged();
}

