#ifndef STORAGEFILETYPE_H
#define STORAGEFILETYPE_H

// Generated by APIGenerator 1.0
// DO NOT EDIT!!!

#include "../../types/telegramobject.h"
#include "../../types/basic.h"

class StorageFileType: public TelegramObject
{
	Q_OBJECT

	Q_ENUMS(Constructors)

	public:
		enum Constructors {
			ctorStorageFileUnknown = 0xaa963b05,
			ctorStorageFileJpeg = 0x7efe0e,
			ctorStorageFileGif = 0xcae1aadf,
			ctorStorageFilePng = 0xa4f63c0,
			ctorStorageFilePdf = 0xae1e508d,
			ctorStorageFileMp3 = 0x528a0677,
			ctorStorageFileMov = 0x4b09ebbc,
			ctorStorageFilePartial = 0x40bc6f52,
			ctorStorageFileMp4 = 0xb3cea0e4,
			ctorStorageFileWebp = 0x1081464c,
		};

	public:
		explicit StorageFileType(QObject* parent = 0);
		virtual void read(MTProtoStream* mtstream);
		virtual void write(MTProtoStream* mtstream);
	protected:
		virtual void compileFlags();

};

#endif // STORAGEFILETYPE_H
