// Generated by APIGenerator 1.0
// DO NOT EDIT!!!

#include "storagefiletype.h"

StorageFileType::StorageFileType(QObject* parent) : TelegramObject(parent)
{
	
}

void StorageFileType::read(MTProtoStream* mtstream) 
{
	this->_constructorid = mtstream->readTLConstructor();
	
	Q_ASSERT((this->_constructorid == StorageFileType::ctorStorageFileUnknown) ||
		 (this->_constructorid == StorageFileType::ctorStorageFileJpeg) ||
		 (this->_constructorid == StorageFileType::ctorStorageFileGif) ||
		 (this->_constructorid == StorageFileType::ctorStorageFilePng) ||
		 (this->_constructorid == StorageFileType::ctorStorageFilePdf) ||
		 (this->_constructorid == StorageFileType::ctorStorageFileMp3) ||
		 (this->_constructorid == StorageFileType::ctorStorageFileMov) ||
		 (this->_constructorid == StorageFileType::ctorStorageFilePartial) ||
		 (this->_constructorid == StorageFileType::ctorStorageFileMp4) ||
		 (this->_constructorid == StorageFileType::ctorStorageFileWebp));
}

void StorageFileType::write(MTProtoStream* mtstream) 
{
	Q_ASSERT((this->_constructorid == StorageFileType::ctorStorageFileUnknown) ||
		 (this->_constructorid == StorageFileType::ctorStorageFileJpeg) ||
		 (this->_constructorid == StorageFileType::ctorStorageFileGif) ||
		 (this->_constructorid == StorageFileType::ctorStorageFilePng) ||
		 (this->_constructorid == StorageFileType::ctorStorageFilePdf) ||
		 (this->_constructorid == StorageFileType::ctorStorageFileMp3) ||
		 (this->_constructorid == StorageFileType::ctorStorageFileMov) ||
		 (this->_constructorid == StorageFileType::ctorStorageFilePartial) ||
		 (this->_constructorid == StorageFileType::ctorStorageFileMp4) ||
		 (this->_constructorid == StorageFileType::ctorStorageFileWebp));
	
	this->compileFlags();
	mtstream->writeTLConstructor(this->_constructorid);
}

void StorageFileType::compileFlags() 
{
	
}

