// Generated by APIGenerator 1.0
// DO NOT EDIT!!!

#include "toppeercategory.h"

TopPeerCategory::TopPeerCategory(QObject* parent) : TelegramObject(parent)
{
	
}

void TopPeerCategory::read(MTProtoStream* mtstream) 
{
	this->_constructorid = mtstream->readTLConstructor();
	
	Q_ASSERT((this->_constructorid == TopPeerCategory::ctorTopPeerCategoryBotsPM) ||
		 (this->_constructorid == TopPeerCategory::ctorTopPeerCategoryBotsInline) ||
		 (this->_constructorid == TopPeerCategory::ctorTopPeerCategoryCorrespondents) ||
		 (this->_constructorid == TopPeerCategory::ctorTopPeerCategoryGroups) ||
		 (this->_constructorid == TopPeerCategory::ctorTopPeerCategoryChannels));
}

void TopPeerCategory::write(MTProtoStream* mtstream) 
{
	Q_ASSERT((this->_constructorid == TopPeerCategory::ctorTopPeerCategoryBotsPM) ||
		 (this->_constructorid == TopPeerCategory::ctorTopPeerCategoryBotsInline) ||
		 (this->_constructorid == TopPeerCategory::ctorTopPeerCategoryCorrespondents) ||
		 (this->_constructorid == TopPeerCategory::ctorTopPeerCategoryGroups) ||
		 (this->_constructorid == TopPeerCategory::ctorTopPeerCategoryChannels));
	
	this->compileFlags();
	mtstream->writeTLConstructor(this->_constructorid);
}

void TopPeerCategory::compileFlags() 
{
	
}

