#ifndef MTPROTOUPDATEHANDLER_H
#define MTPROTOUPDATEHANDLER_H

#define UPDATE_HANDLER MTProtoUpdateHandler::instance()
#define UPDATE_HANDLER_SYNC MTProtoUpdateHandler::instance()->sync()

#include <QObject>
#include "mtprotoreply.h"
#include "../autogenerated/types/types.h"

class MTProtoUpdateHandler : public QObject
{
    Q_OBJECT

    private:
        explicit MTProtoUpdateHandler(QObject *parent = 0);

    public:
        static MTProtoUpdateHandler* instance();
        bool handle(MTProtoReply* mtreply);
        void sync();

    private: // MTProto Raw Replies
        bool handleUpdates(MTProtoReply* mtreply);
        bool handleUpdatesState(MTProtoReply* mtreply);

    private:
        bool handleUpdate(Update* update);
        bool handleUpdateShort(Update* update);
        bool handleUpdateNewAuthorization(Update* update);

    private:
        bool _syncmode;

    private:
        static MTProtoUpdateHandler* _instance;
};

#endif // MTPROTOUPDATEHANDLER_H
