#include "filecache.h"
#include "../../autogenerated/telegramapi.h"
#include "../../types/telegramhelper.h"
#include "telegramcache.h"
#include <QStandardPaths>
#include <QDir>

#define CACHE_FOLDER "cache"

FileCache* FileCache::_instance = NULL;

FileCache::FileCache(QObject *parent) : QObject(parent)
{
    this->_storagepath = QStandardPaths::writableLocation(QStandardPaths::CacheLocation) + QDir::separator() + CACHE_FOLDER;

    QDir dir;
    dir.mkpath(this->_storagepath);
}

FileCache *FileCache::instance()
{
    if(!FileCache::_instance)
        FileCache::_instance = new FileCache();

    return FileCache::_instance;
}

FileObject *FileCache::fileObject(Dialog *dialog)
{
    TLInt id = TelegramHelper::identifier(dialog);

    if(TelegramHelper::isChat(dialog) || TelegramHelper::isChannel(dialog))
    {
        Chat* chat = TelegramCache_chat(id);

        if(chat)
            return this->fileObject(chat);

        return NULL;
    }

    User* user = TelegramCache_user(id);

    if(!user)
        return NULL;

    return this->fileObject(user);
}

FileObject *FileCache::fileObject(User *user)
{
    if(!user->photo() || (user->photo()->constructorId() == TLTypes::UserProfilePhotoEmpty))
        return NULL;

    UserProfilePhoto* userprofilephoto = user->photo();
    return this->fileObject(userprofilephoto->photoSmall(), userprofilephoto->photoBig());
}

FileObject *FileCache::fileObject(Chat *chat)
{
    if(!chat->photo() || (chat->photo()->constructorId() == TLTypes::ChatPhotoEmpty))
        return NULL;

    ChatPhoto* chatphoto = chat->photo();
    return this->fileObject(chatphoto->photoSmall(), chatphoto->photoBig());
}

FileObject *FileCache::fileObject(FileLocation *locthumbnail, FileLocation *locfile)
{
    FileObject* fileobject = new FileObject(this->_storagepath, this);
    connect(fileobject, &FileObject::downloadCompleted, this, &FileCache::processQueue);

    fileobject->setThumbnailLocation(locthumbnail);
    fileobject->setFileLocation(locfile);

    if(this->_queue.isEmpty())
    {
        fileobject->downloadThumbnail();
        return fileobject;
    }

    this->_queue << fileobject;
    return fileobject;
}

void FileCache::processQueue()
{
    if(this->_queue.isEmpty())
        return;

    FileObject* fileobject = this->_queue.takeFirst();
    fileobject->downloadThumbnail();
}
