// Generated by APIGenerator 1.0
// DO NOT EDIT!!!

#include "msgsstatereq.h"


MsgsStateReq::MsgsStateReq(QObject* parent) : TelegramObject(parent)
{
	this->_constructorid = MsgsStateReq::CtorMsgsStateReq;
}

void MsgsStateReq::read(MTProtoStream* mtstream) 
{
	this->_constructorid = mtstream->readTLConstructor();
	
	Q_ASSERT((this->_constructorid == MsgsStateReq::CtorMsgsStateReq));
	
	if(this->_constructorid == MsgsStateReq::CtorMsgsStateReq)
		mtstream->readTLVector<TLLong>(this->_msg_ids, false);
}

void MsgsStateReq::write(MTProtoStream* mtstream) 
{
	Q_ASSERT((this->_constructorid == MsgsStateReq::CtorMsgsStateReq));
	
	this->compileFlags();
	mtstream->writeTLConstructor(this->_constructorid);
	
	if(this->_constructorid == MsgsStateReq::CtorMsgsStateReq)
		mtstream->writeTLVector(this->_msg_ids, false);
}

void MsgsStateReq::compileFlags() 
{
	
}

const TLVector<TLLong>& MsgsStateReq::msgIds() const
{
	return this->_msg_ids;
}

void MsgsStateReq::setMsgIds(const TLVector<TLLong>& msg_ids) 
{
	if(this->_msg_ids == msg_ids)
		return;

	this->_msg_ids = msg_ids;
	emit msgIdsChanged();
}

