#ifndef PONG_H
#define PONG_H

// Generated by APIGenerator 1.0
// DO NOT EDIT!!!

#include "../../types/telegramobject.h"
#include "../../types/basic.h"

class Pong: public TelegramObject
{
	Q_OBJECT

	Q_PROPERTY(TLLong msgId READ msgId WRITE setMsgId NOTIFY msgIdChanged)
	Q_PROPERTY(TLLong pingId READ pingId WRITE setPingId NOTIFY pingIdChanged)

	Q_ENUMS(Constructors)

	public:
		enum Constructors {
			ctorPong = 0x347773c5,
		};

	public:
		explicit Pong(QObject* parent = 0);
		virtual void read(MTProtoStream* mtstream);
		virtual void write(MTProtoStream* mtstream);
	protected:
		virtual void compileFlags();
	public:
		TLLong msgId() const;
		void setMsgId(TLLong msg_id);
		TLLong pingId() const;
		void setPingId(TLLong ping_id);

	signals:
		void msgIdChanged();
		void pingIdChanged();

	private:
		TLLong _msg_id;
		TLLong _ping_id;

};

#endif // PONG_H
