#ifndef DCSESSIONMANAGER_H
#define DCSESSIONMANAGER_H

#include <QObject>
#include "dcsession.h"
#include "dcauthorization.h"
#include "autogenerated/telegramapi.h"

#define DC_MAIN_SESSION DCSessionManager::instance()->mainSession()

class DCSessionManager: public QObject
{
    Q_OBJECT

    private:
        DCSessionManager(QObject* parent = 0);
        DC* createDC(const QString& host, qint16 port, int id);
        DC* createDC(int id);
        void doAuthorization(DCSession* dcsession);
        void initSession(DCSession* dcsession);
        void closeSession(DCSession* dcsession, bool closedc = false);

    public:
        static DCSessionManager* instance();

    public:
        DCSession* mainSession() const;
        DCSession* createMainSession(const QString& host, qint16 port, int id);
        DCSession* createSession(int id);

    private slots:
        void onAuthorized(DC *dc);
        void onAuthorizationReply(MTProtoReply *mtreply);
        void onMigrateDC(int dcid);

    private:
        QHash<DC*, DCAuthorization*> _dcauthorizations;
        QHash<int, DC*> _dclist;
        DCSession* _mainsession;

    private:
        static DCSessionManager* _sessionmanager;
};

#endif // DCSESSIONMANAGER_H
