// Generated by APIGenerator 1.0
// DO NOT EDIT!!!

#include "clientsyncmanager.h"

void ClientSyncManager::syncUpdate(Update* u, UpdatesState* clientstate) 
{
	if(u->constructorId() == TLTypes::UpdateNewMessage)
		ClientSyncManager::syncPts(u->pts(), clientstate);
	else if(u->constructorId() == TLTypes::UpdateDeleteMessages)
		ClientSyncManager::syncPts(u->pts(), clientstate);
	else if(u->constructorId() == TLTypes::UpdateUserPhoto)
		ClientSyncManager::syncDate(u->date(), clientstate);
	else if(u->constructorId() == TLTypes::UpdateContactRegistered)
		ClientSyncManager::syncDate(u->date(), clientstate);
	else if(u->constructorId() == TLTypes::UpdateNewAuthorization)
		ClientSyncManager::syncDate(u->date(), clientstate);
	else if(u->constructorId() == TLTypes::UpdateNewEncryptedMessage)
		ClientSyncManager::syncQts(u->qts(), clientstate);
	else if(u->constructorId() == TLTypes::UpdateEncryption)
		ClientSyncManager::syncDate(u->date(), clientstate);
	else if(u->constructorId() == TLTypes::UpdateEncryptedMessagesRead)
		ClientSyncManager::syncDate(u->date(), clientstate);
	else if(u->constructorId() == TLTypes::UpdateChatParticipantAdd)
		ClientSyncManager::syncDate(u->date(), clientstate);
	else if(u->constructorId() == TLTypes::UpdateReadHistoryInbox)
		ClientSyncManager::syncPts(u->pts(), clientstate);
	else if(u->constructorId() == TLTypes::UpdateReadHistoryOutbox)
		ClientSyncManager::syncPts(u->pts(), clientstate);
	else if(u->constructorId() == TLTypes::UpdateWebPage)
		ClientSyncManager::syncPts(u->pts(), clientstate);
	else if(u->constructorId() == TLTypes::UpdateReadMessagesContents)
		ClientSyncManager::syncPts(u->pts(), clientstate);
	else if(u->constructorId() == TLTypes::UpdateChannelTooLong)
		ClientSyncManager::syncPts(u->pts(), clientstate);
	else if(u->constructorId() == TLTypes::UpdateNewChannelMessage)
		ClientSyncManager::syncPts(u->pts(), clientstate);
	else if(u->constructorId() == TLTypes::UpdateDeleteChannelMessages)
		ClientSyncManager::syncPts(u->pts(), clientstate);
	else if(u->constructorId() == TLTypes::UpdateEditChannelMessage)
		ClientSyncManager::syncPts(u->pts(), clientstate);
	else if(u->constructorId() == TLTypes::UpdateEditMessage)
		ClientSyncManager::syncPts(u->pts(), clientstate);
}

void ClientSyncManager::syncUpdates(Updates* u, UpdatesState* clientstate) 
{
	if(u->constructorId() == TLTypes::UpdateShortMessage)
	{
		ClientSyncManager::syncPts(u->pts(), clientstate);
		ClientSyncManager::syncDate(u->date(), clientstate);
	}
	else if(u->constructorId() == TLTypes::UpdateShortChatMessage)
	{
		ClientSyncManager::syncPts(u->pts(), clientstate);
		ClientSyncManager::syncDate(u->date(), clientstate);
	}
	else if(u->constructorId() == TLTypes::UpdateShort)
		ClientSyncManager::syncDate(u->date(), clientstate);
	else if(u->constructorId() == TLTypes::UpdatesCombined)
	{
		ClientSyncManager::syncDate(u->date(), clientstate);
		ClientSyncManager::syncSeq(u->seq(), clientstate);
	}
	else if(u->constructorId() == TLTypes::Updates)
	{
		ClientSyncManager::syncDate(u->date(), clientstate);
		ClientSyncManager::syncSeq(u->seq(), clientstate);
	}
	else if(u->constructorId() == TLTypes::UpdateShortSentMessage)
	{
		ClientSyncManager::syncPts(u->pts(), clientstate);
		ClientSyncManager::syncDate(u->date(), clientstate);
	}
}

void ClientSyncManager::syncState(UpdatesState* serverstate) 
{
	UpdatesState* clientstate = TelegramConfig_clientState;
	
	ClientSyncManager::syncPts(serverstate->pts(), clientstate);
	ClientSyncManager::syncQts(serverstate->qts(), clientstate);
	ClientSyncManager::syncDate(serverstate->date(), clientstate);
	ClientSyncManager::syncSeq(serverstate->seq(), clientstate);
	ClientSyncManager::syncUnreadCount(serverstate->unreadCount(), clientstate);
}

void ClientSyncManager::syncPts(TLInt pts, UpdatesState* clientstate) 
{
	if(pts <= clientstate->pts())
		return;
	
	clientstate->setPts(pts);
}

void ClientSyncManager::syncQts(TLInt qts, UpdatesState* clientstate) 
{
	if(qts <= clientstate->qts())
		return;
	
	clientstate->setQts(qts);
}

void ClientSyncManager::syncDate(TLInt date, UpdatesState* clientstate) 
{
	if(date <= clientstate->date())
		return;
	
	clientstate->setDate(date);
}

void ClientSyncManager::syncSeq(TLInt seq, UpdatesState* clientstate) 
{
	clientstate->setSeq(seq); // NOTE: How to handle 'seq'?
}

void ClientSyncManager::syncUnreadCount(TLInt unreadcount, UpdatesState* clientstate) 
{
	if(unreadcount <= clientstate->unreadCount())
		return;
	
	clientstate->setUnreadCount(unreadcount);
}

