#ifndef TELEGRAMQML_H
#define TELEGRAMQML_H

// Generated by APIGenerator 1.0
// DO NOT EDIT!!!

#include "../objects/telegramqmlbase.h"
#include "types/types.h"

class TelegramQml: public QObject
{
	Q_OBJECT

	public:
		static void initialize(const QString& uri);

};

#endif // TELEGRAMQML_H
